//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `Montecarlo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MasterWorker;

public class Point extends com.zeroc.Ice.Value
{
    public Point()
    {
    }

    public Point(double x, double y)
    {
        this.x = x;
        this.y = y;
    }

    public double x;

    public double y;

    public Point clone()
    {
        return (Point)super.clone();
    }

    public static String ice_staticId()
    {
        return "::MasterWorker::Point";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1749910346L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeDouble(x);
        ostr_.writeDouble(y);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        x = istr_.readDouble();
        y = istr_.readDouble();
        istr_.endSlice();
    }
}
